{
 "title": "Victron SmartSolar",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "type",
    "label": "Type",
    "query": "SHOW TAG VALUES ON victron WITH KEY = \"type\""
   },
   {
    "name": "device",
    "label": "Device",
    "query": "SHOW TAG VALUES ON victron WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n  <h1 style=\"font-size:3.0em; margin: 0; padding: 0; text-transform: capitalize;\">\n Victron {{data.[0].type}} {{data.[0].device}}\n    <div style=\"font-size:0.6em; font-style: italic; color: #666\">(Ultimo rilievo: {{date data.[0]._timestamp 'DD/MM/YYYY HH:mm:ss'}})</div>\n\n  </h1>\n</center>"
   },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC limit 1"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<center>\n  <h1 style=\"font-size:2.0em; margin: 0; margin-top:0.5em\">\n    Solare\n  </h1>\n</center>"
   },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC limit 1"
    }
   ]
  },
  {
   "title": "Solar power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT solar_power FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Solar power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT solar_power FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device'  AND $timeFilter"
    }
   ]
  },
  {
   "title": "Solar power",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT solar_power FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Rendimento odierno (Yield today)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(yield_today) FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device'"
    }
   ]
  },
  {
   "title": "Rendimento odierno (Yield today)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT yield_today FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Solar power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Battery",
     "query": "SELECT mean(\"solar_power\") FROM victron..$device WHERE $timeFilter AND \"type\"='$type' and \"device\"='$device' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Rendimento odierno (Yield today)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "SELECT mean(\"yield_today\") FROM victron..$device WHERE $timeFilter AND \"type\"='$type' and \"device\"='$device' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<center>\n  <h1 style=\"font-size:2.0em; margin: 0; margin-top:0.5em\">\n    Batteria\n  </h1>\n</center>"
   },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC limit 1"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT battery_voltage FROM victron..$device WHERE \"type\"='$type' AND \"device\"='$device' AND $timeFilter "
    }
   ]
  },
  {
   "title": "Battery charging current",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(battery_charging_current) FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device'"
    }
   ]
  },
  {
   "title": "Battery Power",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "voltage",
     "query": "SELECT last(battery_voltage) as voltage FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Battery charging status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(charge_state) FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device'"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery",
     "query": "SELECT mean(\"battery_voltage\") FROM victron..$device WHERE $timeFilter AND \"type\"='$type' and \"device\"='$device' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Battery charging current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "Battery",
     "query": "SELECT mean(\"battery_charging_current\") FROM victron..$device WHERE $timeFilter AND \"type\"='$type' and \"device\"='$device' GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 50 },
   "options": {
    "content": "<center>\n  <h1 style=\"font-size:2.0em; margin: 0; margin-top:0.5em\">\n    Uscita del carico\n  </h1>\n</center>"
   },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC limit 1"
    }
   ]
  },
  {
   "title": "Corrente del carico (External device load)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(external_device_load) FROM victron..$device WHERE \"type\"='$type' and \"device\"='$device'"
    }
   ]
  },
  { "type": "mxswat-separator-panel", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 57 },
   "options": {
    "content": "<center>\n  <h1 style=\"font-size:2.0em; margin: 0; margin-top:0.5em\">\nTabella dati\n  </h1>\n</center>"
   },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC limit 1"
    }
   ]
  },
  {
   "type": "briangann-datatable-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "query": "SELECT * FROM victron..$device WHERE $timeFilter AND \"type\"='$type' AND \"device\"='$device' ORDER BY time DESC"
    }
   ]
  }
 ]
}